version: "3"
services:
  api:
    container_name: backend_container
    restart: on-failure
    build:
      dockerfile: Dockerfile.dev
      context: "./back"
    volumes:
      - /app/node_modules
      - ./back:/app
    ports:
      - "4000:4000"

  client:
    container_name: frontend_container
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./front
    volumes:
      - /app/node_modules
      - ./front:/app
    ports:
      - "3000:3000"